/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.karla.msicu.emociones.curso;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Developer
 */
public class EditarVideo extends javax.swing.JFrame {
    Tema parentView = null;
    int id = 0;
    /**
     * Creates new form NuevoCurso
     */
    public EditarVideo(Tema parentView, int id) throws SQLException, ClassNotFoundException {
        initComponents();
        this.parentView = parentView;
        this.id = id;
        setData();
    }
    
    private void setData() throws ClassNotFoundException, SQLException{
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection connection = null;
        connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/emociones?serverTimezone=UTC", "emociones", "emociones");
        String query = "select * from video where idtema = ?";
        PreparedStatement preparedStatemet = connection.prepareStatement(query);
        preparedStatemet.setInt(1, id);
        ResultSet rs = preparedStatemet.executeQuery();
        rs.first();
        CampoNombre.setText(rs.getString("nombre"));
        CampoVideo.setText(rs.getString("curso_idcurso"));        
        connection.close();
    }
    
    private void saveCurso() throws ClassNotFoundException, SQLException{
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection connection = null;
        connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/emociones?serverTimezone=UTC", "emociones", "emociones");
        String nombre = CampoNombre.getText();
        String curso_idcurso = CampoVideo.getText();
        if(!nombre.equals("")){
            String query = "update tema set nombre = ?,curso_idcurso = ?  where idtema = ?";
            PreparedStatement preparedStatemet = connection.prepareStatement(query);
            preparedStatemet.setString (1, nombre);
            preparedStatemet.setString (2, curso_idcurso);
            preparedStatemet.setInt(3, id);
            preparedStatemet.execute();
            parentView.fillTable();
            connection.close();
            this.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GuardarNombre = new javax.swing.JButton();
        EtiquetaNombre = new javax.swing.JLabel();
        CampoNombre = new javax.swing.JTextField();
        EtiquetaCurso = new javax.swing.JLabel();
        CampoVideo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nuevo Curso");

        GuardarNombre.setText("Guardar");
        GuardarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarNombreActionPerformed(evt);
            }
        });

        EtiquetaNombre.setText("Nombre del vídeo");

        EtiquetaCurso.setText("Reproducido");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(EtiquetaNombre))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(159, 159, 159)
                                .addComponent(GuardarNombre))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(EtiquetaCurso)))
                        .addGap(0, 156, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CampoVideo)
                            .addComponent(CampoNombre))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EtiquetaNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(CampoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EtiquetaCurso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CampoVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GuardarNombre)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarNombreActionPerformed
        try {
            saveCurso();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(EditarVideo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_GuardarNombreActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoNombre;
    private javax.swing.JTextField CampoVideo;
    private javax.swing.JLabel EtiquetaCurso;
    private javax.swing.JLabel EtiquetaNombre;
    private javax.swing.JButton GuardarNombre;
    // End of variables declaration//GEN-END:variables
}
